### ISSUE TITLE
Stripe error

### ISSUE THREAD

**Issue by jackd0uet** [JuicingJ/upskill_saas_tutorial#2]
Hi there,

I'm also working through the tutorial and I'm having issues with my Stripe implementation and I have seen that you have progressed past this point so there must be a fix. Basically I am struggling to find on Stripes new UI where you enter plan IDs and have been unable to find where they are located by looking online. I was just wondering how you got around this and maybe helping me out if you could.

Thanks,
Jack

**Comment by JuicingJ** [comment]
Hi

I wish I could help you through your problem. I faced the same problem you
are facing currently. Additionally, I faced problems with integrating
mailgun and heroku as well. After one of the videos between 145 and 155, my
site stopped launching only. I pushed through the lessons to understand
what he was doing and the implications of the same. However, the prototype
on my end does not work the way it does in the videos. Sorry I couldn't be
of help.

If you are able to solve this issue, do let me know.

Kind regards

**Comment by jackd0uet** [comment]
Hi, thanks for getting back to me.

It seems the course is quite out of date because everyone I have spoken to has said similar. What did you move onto after you finished the course if you don't mind me asking?

Thanks,

Jack

**Comment by JuicingJ** [comment]
Hi

No worries! Yes it seems the same to me too. However, the advice of the
tutor still holds and that's my plan now. Am gonna read documentation as he
suggested and start a few projects of my own to test the learning from this
course. Although, I'll use the latest versions of ruby and other softwares
as per requirement.

Do let me know if and how you progress with the course.

Kind regards
